"""
Stateless C++ RL environment (CarRacingEnv)
"""
from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['RacingEnv', 'VecRacingEnv']
class RacingEnv:
    @staticmethod
    def action_dim() -> int:
        ...
    @staticmethod
    def num_agents() -> int:
        ...
    @staticmethod
    def obs_dim() -> int:
        ...
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def current_agents(self) -> numpy.typing.NDArray[numpy.int32]:
        ...
    def render_state(self) -> tuple:
        ...
    def reset(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def step(self, action: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64]]:
        ...
class VecRacingEnv:
    @staticmethod
    def action_dim() -> int:
        ...
    @staticmethod
    def num_agents() -> int:
        ...
    @staticmethod
    def obs_dim() -> int:
        ...
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def current_agents(self) -> numpy.typing.NDArray[numpy.int32]:
        ...
    def render_state(self) -> tuple:
        ...
    def reset(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def step(self, actions: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64]]:
        ...
