"""
Stateless C++ RL environment (RobotEnv)
"""
from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['RobotEnv', 'VecRobotEnv']
class RobotEnv:
    @staticmethod
    def act_dim() -> int:
        ...
    @staticmethod
    def obs_dim() -> int:
        ...
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def render_state(self) -> tuple:
        ...
    def reset(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def step(self, action: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64]]:
        ...
class VecRobotEnv:
    @staticmethod
    def act_dim() -> int:
        ...
    @staticmethod
    def obs_dim() -> int:
        ...
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def render_state(self) -> tuple:
        ...
    def reset(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def step(self, action: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float64]]:
        ...
